CREATE TABLE APPLICATION_USER (
  USER_ID   VARCHAR(64)   NOT NULL,
  USERNAME  VARCHAR(32)   NOT NULL  UNIQUE,
  PASSWORD  VARCHAR(64)   NOT NULL,
  SALT      VARCHAR(64)   NOT NULL,
  ROLE      VARCHAR(32)   NOT NULL,
  FULLNAME  VARCHAR(256)  NOT NULL,
  PRIMARY KEY(USER_ID)
);

CREATE TABLE CONTAINER_CREATOR (
  CREATOR_ID  VARCHAR(64) NOT NULL,
  USER_ID     VARCHAR(64) NOT NULL,
  PRIMARY KEY(CREATOR_ID)
);
